export enum ActionTypes {
      //Boards
      GET_ALL_BOARDS,
      GET_ALL_BOARDS_SUCCESS,
      GET_ALL_BOARDS_ERROR,
      CREATE_BOARD,
      CREATE_BOARD_SUCCESS,
      CREATE_BOARD_ERROR,
      UPDATE_BOARD,
      UPDATE_BOARD_SUCCESS,
      UPDATE_BOARD_ERROR,
      DELETE_BOARD,
      DELETE_BOARD_SUCCESS,
      DELETE_BOARD_ERROR,
      SET_ACTIVE_BOARD,

      //Lists
      GET_ALL_LISTS,
      GET_ALL_LISTS_SUCCESS,
      GET_ALL_LISTS_ERROR,
      ADD_LIST,
      ADD_LIST_SUCCESS,
      ADD_LIST_ERROR,

      //Cards
      GET_ALL_CARDS,
      GET_ALL_CARDS_SUCCESS,
      GET_ALL_CARDS_ERROR,
}
