export enum ActionTypes {
      GET_ALL_BOARDS,
      GET_ALL_BOARDS_SUCCESS,
      GET_ALL_BOARDS_ERROR,
      CREATE_BOARD,
      CREATE_BOARD_SUCCESS,
      CREATE_BOARD_ERROR,
      DELETE_BOARD,
      DELETE_BOARD_SUCCESS,
      DELETE_BOARD_ERROR,
      SET_ACTIVE_BOARD,
}
